/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/Layout/AppLayout.vue')['default']
    BottomNavigation: typeof import('./src/components/Layout/BottomNavigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarChip: typeof import('@varlet/ui')['_ChipComponent']
    VarDatePicker: typeof import('@varlet/ui')['_DatePickerComponent']
    VarDialog: typeof import('@varlet/ui')['_DialogComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarOption: typeof import('@varlet/ui')['_OptionComponent']
    VarPicker: typeof import('@varlet/ui')['_PickerComponent']
    VarPopup: typeof import('@varlet/ui')['_PopupComponent']
    VarSelect: typeof import('@varlet/ui')['_SelectComponent']
  }
}
